import Header from "./header";
import Head from "next/head";

function Layout({ children, title }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col min-h-screen">
        <Header />
        <div className="flex-1 flex flex-col">{children}</div>
      </div>
    </>
  );
}

export default Layout;
