import Head from "next/head";
import Footer from "./footer";
import Header from "./header";

function Layout(props) {
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col min-h-screen">
        <Header />
        <div className="flex-auto flex flex-col text-zinc-800">
          {props.children}
        </div>
        <Footer />
      </div>
    </>
  );
}

export default Layout;
