# Generated by Django 4.1 on 2022-11-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification",
            field=models.TextField(max_length=200),
        ),
    ]
