# Generated by Django 4.1 on 2022-08-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("in_file", models.FileField(upload_to="front/files/input")),
                ("t", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MyOutFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("out_file", models.FileField(upload_to="front/files/output")),
            ],
        ),
    ]
