# Generated by Django 4.1 on 2022-11-01 11:11

from django.db import migrations, models
import django.db.models.deletion
import translit.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "in_file",
                    models.FileField(
                        storage=translit.storage.MyStorage(
                            location="/home/samandar/samandar/airiuz/tilim.uz/Backend/front/files/input"
                        ),
                        upload_to="",
                    ),
                ),
                ("t", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MyOutFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "out_file",
                    models.FileField(
                        storage=translit.storage.MyStorage(
                            location="/home/samandar/samandar/airiuz/tilim.uz/Backend/front/files/output"
                        ),
                        upload_to="",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextLikeUnlike",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("like", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="TypeFastModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="TypeFastOutModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_id", models.IntegerField()),
                ("text", models.CharField(max_length=500)),
                ("true_answers", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name="NameofTop",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type_fast_out_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="translit.typefastoutmodel",
                    ),
                ),
            ],
        ),
    ]
