# Generated by Django 4.2.13 on 2024-06-20 09:05

from django.db import migrations, models
import translit.storage


class Migration(migrations.Migration):

    dependencies = [
        ('translit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topusers',
            name='chars',
        ),
        migrations.RemoveField(
            model_name='topusers',
            name='true_answers',
        ),
        migrations.AddField(
            model_name='topusers',
            name='wpm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='in_file',
            field=models.FileField(storage=translit.storage.MyStorage(location='/Users/giyosoripov/PycharmProjects/tilim.uz/Backend/front/files/input'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='myoutfile',
            name='out_file',
            field=models.FileField(storage=translit.storage.MyStorage(location='/Users/giyosoripov/PycharmProjects/tilim.uz/Backend/front/files/output'), upload_to=''),
        ),
    ]
