# Generated by Django 4.1.1 on 2022-09-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myfile",
            name="in_file",
            field=models.FileField(upload_to="input"),
        ),
        migrations.AlterField(
            model_name="myoutfile",
            name="out_file",
            field=models.FileField(upload_to="output"),
        ),
    ]
