# Generated by Django 4.2 on 2023-04-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translit', '0002_alter_myfile_in_file_alter_myoutfile_out_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='typefastoutmodel',
            name='alpha',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
