# Generated by Django 4.1.1 on 2022-10-03 06:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translit", "0003_alter_myfile_in_file_alter_myoutfile_out_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeFastModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name="myfile",
            name="in_file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="/home/samandar/samandar/textidtmuz/front/files/input"
                ),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="myoutfile",
            name="out_file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="/home/samandar/samandar/textidtmuz/front/files/output"
                ),
                upload_to="",
            ),
        ),
    ]
