# Generated by Django 4.1 on 2022-10-06 08:08

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translit", "0004_typefastmodel_alter_myfile_in_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeFastOutModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_id", models.IntegerField()),
                ("text", models.CharField(max_length=500)),
                ("true_answers", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="myfile",
            name="in_file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="/home/samandar/samandar/airiuz/tilim.uz/Backend/front/files/input"
                ),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="myoutfile",
            name="out_file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="/home/samandar/samandar/airiuz/tilim.uz/Backend/front/files/output"
                ),
                upload_to="",
            ),
        ),
        migrations.CreateModel(
            name="NameofTop",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type_fast_out_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="translit.typefastoutmodel",
                    ),
                ),
            ],
        ),
    ]
