# Generated by Django 4.2 on 2023-04-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translit', '0005_rename_alpha_topuers_t'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopUers',
            new_name='TopUsers',
        ),
    ]
