# Generated by Django 4.1.2 on 2022-10-20 09:57

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translit', '0005_typefastoutmodel_alter_myfile_in_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='in_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\REST\\tilimuz\\Backend\\front\\files\\input'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='myoutfile',
            name='out_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\REST\\tilimuz\\Backend\\front\\files\\output'), upload_to=''),
        ),
        migrations.CreateModel(
            name='TextLikeUnlike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('like', models.BooleanField()),
            ],
            options={
                'unique_together': {('text', 'like')},
            },
        ),
    ]
