# Generated by Django 4.1 on 2022-10-21 06:45

from django.db import migrations, models
import translit.storage


class Migration(migrations.Migration):

    dependencies = [
        ("translit", "0007_alter_textlikeunlike_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myfile",
            name="in_file",
            field=models.FileField(
                storage=translit.storage.MyStorage(
                    location="/home/samandar/samandar/airiuz/tilim.uz/Backend/front/files/input"
                ),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="myoutfile",
            name="out_file",
            field=models.FileField(
                storage=translit.storage.MyStorage(
                    location="/home/samandar/samandar/airiuz/tilim.uz/Backend/front/files/output"
                ),
                upload_to="",
            ),
        ),
    ]
