# Generated by Django 4.1.2 on 2022-10-25 10:55

from django.db import migrations, models
import translit.storage


class Migration(migrations.Migration):

    dependencies = [
        ('translit', '0008_alter_myfile_in_file_alter_myoutfile_out_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='myfile',
            name='in_file',
            field=models.FileField(storage=translit.storage.MyStorage(location='/mnt/d/REST/tilimuz/Backend/front/files/input'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='myoutfile',
            name='out_file',
            field=models.FileField(storage=translit.storage.MyStorage(location='/mnt/d/REST/tilimuz/Backend/front/files/output'), upload_to=''),
        ),
    ]
